# The capabilities directory should contain the LLM generated capability files.
capabilities_cfg:
  saved_capabilities_dir: <dir_where_capabilities_are_stored>
  domain: math

embedding_cfg:
  # The embedding model name used to generate capability embeddings used for filtering.
  embedding_model: "text-embedding-3-small" # "text-embedding-3-small" or "text-embedding-3-large"
  embedding_size: 512
  # The cosine similarity threshold for filtering capabilities based on their embeddings.
  filtering_similarity_threshold: 0.9

dimensionality_reduction_cfg:
  # Dimensionality reduction method generates the low dimensional encodings.
  reduce_dimensionality_method: "pca" # "t-sne" or "pca".
  reduced_dimensionality_size: 2
  # The following parameter will be used only if you are using t-SNE.
  tsne_perplexity: 8 # Choose this hyperparameter based on the number of capabilities you have.
  normalize_output: False

embedding_visualization_cfg:
  save_dir: <save_dir>
  plot_name: "Non-normalized PCA Embeddings"
  show_point_ids: true # Set to true when plotting a small number of capabilities.

heatmap_cfg:
  save_dir: <save_dir>
  plot_name: "embedding_heatmap"
  add_squares: true

defaults:
  - _self_
