name: code checks

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - '**.ipynb'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - '**.ipynb'

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies and check code
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry env use '3.10'
          source $(poetry env info --path)/bin/activate
          poetry install --with test --all-extras
          pre-commit run --all-files

      - name: Security audit
        run: |
          source $(poetry env info --path)/bin/activate
          pip-audit
